# Cloudbuild pipeline for a build with an image
# and call out to voucher signer
steps:
  # Build a 'good' image
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
      - -c
      - |
        docker build -t gcr.io/$PROJECT_ID/test-image-for-voucher:latest .
    id: build
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
    - -c
    - |
      docker push gcr.io/$PROJECT_ID/test-image-for-voucher:latest &&
      docker image inspect gcr.io/$PROJECT_ID/test-image-for-voucher:latest --format '{{index .RepoDigests 0}}' > image-digest.txt &&
      cat image-digest.txt
    id: push
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
    - -c
    - |
      curl -X POST \
      -H "Content-Type: application/json" \
      -d "{\"image_url\": \"$(/bin/cat image-digest.txt)\"}" \
      https://voucher-test-myyhkwusua-uc.a.run.app/all
    waitFor: ["push"]
    id: vulnsign
images: ['gcr.io/$PROJECT_ID/test-image-for-voucher:latest']